import os
import shutil
import uuid
from contextlib import asynccontextmanager
from fastapi import FastAPI, UploadFile, File, HTTPException
from fastapi.staticfiles import StaticFiles
from fastapi.middleware.cors import CORSMiddleware
from matlab_bridge import bridge

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
UPLOAD_DIR = os.path.join(BASE_DIR, "uploads")
STATIC_DIR = os.path.join(BASE_DIR, "static_results")

os.makedirs(UPLOAD_DIR, exist_ok=True)
os.makedirs(STATIC_DIR, exist_ok=True)

@asynccontextmanager
async def lifespan(app: FastAPI):
    bridge.start_engine()
    yield
    bridge.stop_engine()

app = FastAPI(title="Foresight Backend API", lifespan=lifespan)

# Enable CORS for frontend integration
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Mount the static directory to expose saved output images over HTTP
app.mount("/static", StaticFiles(directory=STATIC_DIR), name="static")

def copy_to_static(temp_path: str, prefix: str) -> str:
    """Copies a temp file generated by MATLAB to static_results with a unique filename."""
    if not temp_path or not os.path.exists(temp_path):
        return ""
    
    unique_id = uuid.uuid4().hex[:8]
    ext = os.path.splitext(temp_path)[1] or ".png"
    filename = f"{prefix}_{unique_id}{ext}"
    destination = os.path.join(STATIC_DIR, filename)
    
    shutil.copy(temp_path, destination)
    
    # Return full web URL so the frontend can display images directly
    return f"http://127.0.0.1:8000/static/{filename}"

@app.post("/api/screening/analyze")
async def analyze_screening(file: UploadFile = File(...)):
    try:
        file_path = os.path.join(UPLOAD_DIR, file.filename)
        with open(file_path, "wb") as buffer:
            shutil.copyfileobj(file.file, buffer)

        # Execute MATLAB analysis pipeline
        raw_result = bridge.analyze_image(file_path)

        # Copy temp output images to servable static directory
        gradcam_url = copy_to_static(raw_result.get("gradCAMImage"), "gradcam")
        overlay_url = copy_to_static(raw_result.get("lesionOverlay"), "overlay")
        loc_url = copy_to_static(raw_result.get("localizationImage"), "loc")

        # Update paths in final payload to web URLs
        raw_result["gradCAMImage"] = gradcam_url
        raw_result["lesionOverlay"] = overlay_url
        raw_result["localizationImage"] = loc_url

        return {
            "success": True,
            "filename": file.filename,
            "result": raw_result
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
